version: '3'
services:
  jielong-web:
    build: .
    ports:
      - 8080:8080
    networks:
      - jielong-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://jielong-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: jielonguser
      SPRING_DATASOURCE_PASSWORD: jielong123
    depends_on:
      - jielong-pgadmin
  jielong-postgres:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - jielong-network
    environment:
      POSTGRES_USER: jielonguser
      POSTGRES_PASSWORD: jielong123
  jielong-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    networks:
      - jielong-network
    environment:
      PGADMIN_DEFAULT_EMAIL: jielonguser@gtt.com
      PGADMIN_DEFAULT_PASSWORD: jielong123
    depends_on:
      - jielong-postgres

networks:
  jielong-network:
    driver: bridge